name: Install and Cache Dependencies
description: Installs and caches project dependencies

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      with:
        clean: false

    - name: Set up Mise
      uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
      with:
        version: "2025.9.2"
        install: true
        cache: true

    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: src/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm install
      shell: bash
